export const LOGIN_SUBMIT_REQUEST = 'LOGIN.SUBMIT_REQUEST'

export const CHECKPOINT_GET_LIST_REQ = 'CHECKPOINT.GET_LIST_REQ'
export const CHECKPOINT_GET_LIST_SUC = 'CHECKPOINT.GET_LIST_SUC'
export const CHECKPOINT_GET_LIST_ERR = 'CHECKPOINT.GET_LIST_ERR'
export const CHECKPOINT_OPEN_REQ = 'CHECKPOINT.OPEN_REQ'
export const CHECKPOINT_RESTORE_REQ = 'CHECKPOINT.RESTORE_REQ'
export const CHECKPOINT_CLOSE_REQ = 'CHECKPOINT.CLOSE_REQ'

export const SEARCH_GET_PLATE_REQ = 'SEARCH.GET_PLATE_REQ';
export const SEARCH_GET_PLATE_SUC = 'SEARCH.GET_PLATE_SUC';
export const SEARCH_GET_PLATE_ERR = 'SEARCH.GET_PLATE_ERR';

export const QRSCAN_CHECK_ENCRYPT_REQ = 'QRSCAN._CHECK_ENCRYPT_REQ';
export const QRSCAN_CHECK_ENCRYPT_SUC = 'QRSCAN.CHECK_ENCRYPT_SUC';
export const QRSCAN_CHECK_ENCRYPT_ERR = 'QRSCAN.CHECK_ENCRYPT_ERR';
